apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: st-ab5-statsenko
spec:
  selector:
    app: hello-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP